In [2]:
import numpy as np

In [3]:
# произведение матриц
A=np.random.randint(5, 12, (3,3))
B=np.random.randint(-2, 4, (3,3))

In [4]:
A

array([[10, 11,  9],
       [10,  8, 10],
       [ 8,  6,  8]])

In [5]:
B

array([[ 3, -1,  3],
       [ 0, -1,  2],
       [ 1,  0, -1]])

In [6]:
# Поэлементное умножение
A*B

array([[ 30, -11,  27],
       [  0,  -8,  20],
       [  8,   0,  -8]])

In [ ]:
# тип np.matrix
A_m=np.matrix(A)
B_m=np.matrix(B)
print(A_m*B_m)

In [ ]:
# Матричное умножение
np.dot(A,B)

In [ ]:
# Матричное умножение
A@B

In [ ]:
# Порядок умножения AB != BA
B@A

In [ ]:
# Умножение прямоугольных матриц возможно не в любом порядке
A=np.random.randint(5, 12, (3,5))
B=np.random.randint(-2, 4, (5,2))
print('A:\n',A)
print('B:\n',B)

In [ ]:
# Умножение прямоугольных матриц возможно не в любом порядке
A@B

In [ ]:
# Умножение прямоугольных матриц возможно не в любом порядке
B@A

In [ ]:
# размер произведения матриц
print('shape of A:', np.shape(A))
print('shape of B:', np.shape(B))
print('shape of AB:', np.shape(A@B))

In [ ]:
# умножение на специальные матрицы
A=np.random.randint(-4, 4, (4,4))
D=np.diag([1,2,0,-1])
print('A:\n',A)
print('D:\n',D)
print('AD:\n',A@D)
print('DA:\n',D@A)

In [ ]:
# умножение на одномерный массив numpy
A=np.array([[1,0,1],[1,1,1]])
b=np.array([-3,4,5])
A@b

In [ ]:
b@A

In [ ]:
# матрица Грама ортогональной системы векторов
x=np.array([1,1,1])
y=np.array([1,0,-1])
z=np.array([-1,2,-1])
A=np.array([x,y,z])
print (A, type(A))

In [ ]:
# матрица Грама ортогональной системы векторов
A@A.T

In [ ]:
# матрица Грама ортонормированной системы векторов
x_norm=x/np.linalg.norm(x)
y_norm=y/np.linalg.norm(y)
z_norm=z/np.linalg.norm(z)
A_norm=np.array([x_norm,y_norm,z_norm])
print (A_norm, type(A_norm))

In [ ]:
# матрица Грама ортонормированной системы векторов
A_norm@A_norm.T

In [ ]:
# ортонормированные системы рулят! :)
np.round(A_norm@A_norm.T,1)